---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
        when: (ansible_facts['distribution'] != "Fedora")
      - name: Print fact
        debug:
          msg: "{{ var_test }}"
        when: (ansible_facts['distribution'] == "Fedora")