FROM pycontribs/ubuntu:latest
ARG ssh_prv_key
ARG ssh_pub_key
RUN apt-get update && \
    apt-get install -y openssh-server
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh

RUN echo "$ssh_prv_key" > /root/.ssh/id_rsa && \
echo "$ssh_pub_key" > /root/.ssh/id_rsa.pub && \
chmod 600 /root/.ssh/id_rsa && \
chmod 600 /root/.ssh/id_rsa.pub

EXPOSE 52022:22
